### ISSUE TITLE
XCodebuild error with WebDriverAgent

### ISSUE THREAD

**Issue by MadeinFrance** [kelset/react-native-e2e-jest-appium-webdriverio#1]
Thanks a lot for this contribution, it works like a charm on Android.

I have an issue on iOS: I can compile the project with `yarn ios` but when starting the test with Appium it cannot compile and launch the `WebDriverAgent`:

With XCode 14.2:

`ld: cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64`

I have all the necessary Appium dependencies for version 1.22.3 but the command `appium driver install xcuitest` is not recognized.

Side note: I see that FB has moved away from WebDriverAgent in favor of [IDB](https://github.com/facebook/idb/)

**Comment by kelset** [comment]
thanks for reporting, I haven't tested this repo in a while so it could be that something doesn't work. Let me try it locally and report back in a few hrs

**Comment by kelset** [comment]
yeah actually it's been more than 6 months, and the repo is on 0.69 - I can try to upgrade it to 0.71 and then come back here and let you know.. but it's going to take some time 😅

**Comment by MadeinFrance** [comment]
Thanks.

That won't be necessary, I could find a solution by exploring the Appium node_modules and install xcuitest. 

"It works" but it feels hacky and needs to be documented for other devs. I can look further into it for PR.

**Comment by kelset** [comment]
@MadeinFrance sounds good - your issue also made me consider going to RN0.71 + Appium v2.0 so I might attempt that soon

**Comment by kelset** [comment]
tried to do some work here: https://github.com/kelset/react-native-e2e-jest-appium-webdriverio/pull/2 and while the upgrade to RN71 of the app itself is fine, the test side of things just fails with `SIGSEGV` and I don't have a good idea of what's going on anymore. I'm pausing work on that for the time being, any help would be appreciated.
